### ISSUE TITLE
How to bind my own `go ffi`?

### ISSUE THREAD

**Issue by suzumiyasmith** [andyarvanitis/purescript-native#42]
As mentioned in the wiki, binding your own `go ffi` requires a file "XXX.go", which contains package name and function exports.
But where should I put it?
Should it like common purescript JS FFI, putting files in the same folder, e.g. `XXX.purs` `XXX.js` under `src/`
Or could it be put anywhere and referring it with `purescript-native/ffi_loader.go`
In a nutshell, what is the recommended file structure (using `spago`)?

**Comment by andyarvanitis** [comment]
The go ffi uses the go module system and its conventions, so the locations are typically in a source code repository via something like git/github. So for example, the standard libraries are at `github.com/purescript-native/go-ffi`. However, per go's module system, you can specify a local redirect (`replace`) in your project's `go.mod` file. This is handy while you're still testing. An example would be:
```
module project.localhost/example
...
replace github.com/purescript-native/go-ffi => /Users/andy/Projects/PureScript/purescript-go-ffi
...
```
 .
You should start with with the project's generated `go.mod` file, and consult go's own module system docs for general usage details.

Hope that helps.

**Comment by suzumiyasmith** [comment]
Thanks for answering.
But I am still wondering how to use a foreign function.
For example, there is a function in `go` which I wanna bind and use in purs:
`$ cat PP.go`
```go
package purescript_pipipi
import (
  . "github.com/purescript-native/go-runtime"
  "math"
)
func init() {
  exports := Foreign("PP")
  exports["abs"] = func(x_ Any) Any {
    x, _ := x_.(float64)
    return math.Abs(x)
  }
}
```
And I want use it in a `purs` file like,
`$ cat PP.purs`
```purescript
module PP where          
 
foreign import abs :: Number -> Number

```
How could I make it work?
Importing it to other modules `spago build` throw out errors saying `Unkown Value PP.abs`
Where should I put my `go.mod` `go.sum` `PP.purs` `PP.go` and modify `go.mod` `purescript-native/go.mod` generated by default?

(maybe I am not pro in go, running `go mod init` in my project requires specifying project name )

**Comment by andyarvanitis** [comment]
You shouldn't need to deal with much of that, since the `psgo` tool (via `spago`) does it for you. For example, you generally don't need to do `go mod init` on your own. Make sure you're using the latest version of `spago`, otherwise the non-js backend support won't be there. It sounds like maybe you don't, given your "Unknown Value" build error (or maybe you missed a `spago.dhall` configuration step).

I recommend you start from a clean project, and make sure to follow the "getting started" steps at the bottom of this page: https://github.com/andyarvanitis/purescript-native/blob/golang/README-go.md

Once you've followed those steps (and assuming you got a successful go-based build), you should be able to see how the standard libraries and their FFI are pulled in – and combined with the things I mentioned earlier in this thread, add your own.

**Comment by suzumiyasmith** [comment]
Thanks for your patience again. (for a newbie here)

This time I tried to add ffi directly to `ffi_loader.go ` under `purescirpt-native` folder
All I want is calling my own ffi `abs` from `math` in go.
But it still does not work, throwing
```
[info] Installation complete.
Compiling Main
Error found:
in module Main
at src/Main.purs:12:15 - 12:21 (line 12, column 15 - line 12, column 21)

  Unknown value PP.abs
```
Here is my project folder:
https://github.com/suzumiyasmith/purescript-pipipi

**Comment by andyarvanitis** [comment]
No problem. Your compilation error is at the purescript syntax level, not anything to do with FFI, go, or spago. When you `import PP` in purescript, you don't automatically get qualified values. You have to either `import PP as PP` or just reference the values unqualified.

**Comment by suzumiyasmith** [comment]
Thanks. It works.
