### ISSUE TITLE
Running tests on the go backend

### ISSUE THREAD

**Issue by drewolson** [andyarvanitis/purescript-native#45]
I added some tests to my example project in [this](https://github.com/drewolson/purs-native-example/commit/8c1a5306925f244f427afa380850057aaced8345) commit. However, when I run `spago test` it builds and runs my `Main` module instead.

How should I be running my tests?

**Comment by andyarvanitis** [comment]
There's no support for running tests yet, but it's forthcoming (via changes to both `psgo` and `spago`).

**Comment by i-am-the-slime** [comment]
Can we reopen this? I was just about to ask the same thing.

**Comment by andyarvanitis** [comment]
Thanks, I'm fine with that, and someone else might see it and want to tackle it.

**Comment by i-am-the-slime** [comment]
Can you give some hints on how to do this?

**Comment by andyarvanitis** [comment]
It's been a while since I've looked at it, but from what I just read in the spago PR, we'll need to make sure we pass the right module info specified in `psgo --run` to `go run`. That code is in `app/Main.hs`. The purescript convention of module `Test.Main` having a `main` function should ensure this functions correctly. The current code might already be close to doing what it needs, but I'd need to look.

**Comment by andyarvanitis** [comment]
Ok, I just took a closer look, and a few things are needed. `psgo --run Main.main` needs to be changed to translate `Main.main` into the go path, e.g. `output/Main/Main.go`. This would result in command `go run output/Main/Main.go`.

Additionally, the psgo codegen which creates a go `main()` function in the module specifically named `Main` needs to also do this for `Test.Main`, so that `psgo --run Test.Main.main` will also work (yielding `go run output/Test.Main/Test_Main.go`).

Ideally, it should be even more flexible than that, and respect the particular function name specified (not just `main`), but that has its own complications for go.

It would also be nice to use `go test` and its conventions/names instead, but probably not worth pursuing right now.

**Comment by andyarvanitis** [comment]
Ugh, go is even more particular that I thought. The go package name *also* needs to be `main` (and it's case-sensitive) for any invocation of `go run` to work with it. So that means the psgo code that converts ps module name `Main` to go package name `main` and generates a `main()` function also needs to do this for `Test.Main`. Directory and filenames don't appear to matter.

**Comment by andyarvanitis** [comment]
@i-am-the-slime Specifically, look to make changes in `src/CodeGen/IL/Printer.hs` [here](https://github.com/andyarvanitis/purescript-native/blob/d22d4584288f4a9919fe044b85de80696e7711c4/src/CodeGen/IL/Printer.hs#L452) and [here](https://github.com/andyarvanitis/purescript-native/blob/d22d4584288f4a9919fe044b85de80696e7711c4/src/CodeGen/IL/Printer.hs#L485).
